### ISSUE TITLE
Assigning async to class constructor (new())?

### ISSUE THREAD

**Issue by rb1147x** [basro/hx-jsasync#7]
`A class constructor can't have a return value` is the error shown by the compiler if you try to assign a return value to `new()`.

Is there a way to assign `async` to a constructor or is that just not something that's possible even though the JS output might just be yet another function?

Thanks.

**Comment by basro** [comment]
This is something that is not supported in Javascript so I wouldn't recommend trying.

The usual pattern is to use an async static method (for example `createFoo():Promise<Foo>`) that will eventually call your constructor and return an instance of your object.

**Comment by rb1147x** [comment]
Okay, that's how I've been implementing it, but wasn't sure if there was a better way.

Thanks!
